name: neverthrow
description: neverthrow-inspired error library for Dart.
version: 1.0.0
repository: https://github.com/hambergerpls/neverthrow

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  mockito: ^5.4.4

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^2.0.0
  test: ^1.21.0
